server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
         # filters:
           # - name: CircuitBreaker
            #  args:
             #    name: USER-SERVICE
               #  fallbackuri: forward:/userServiceFallback

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
          #filters:
           # - name: CircuitBreaker
            #  args:
             #   name: HOTEL-SERVICE
                #fallbackuri: forward:/hotelServiceFallback

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
         # filters:
          #  - name: CircuitBreaker
           #   args:
            #    name: RATING-SERVICE
             #   #fallbackuri: forward:/ratingServiceFallback

  config:
    import: configserver:http://localhost:8086

#okta configuration

okta:
  oauth2:
    issuer: https://dev-34099492.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7y3blndIXkrQpJ5d7
    client-secret: 3AePzYCVPtkusLcoLefK1E0xq8Sc1Ri8PjJ5UEIn
    scopes: openid, profile, email, offline_access


