server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver



  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8086

