server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8086

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      CktBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  #retry:
    #instances:
     # CktBreaker:
      #  maxAttempts: 3
       # waitDuration: 2s
