server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-34099492.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oa7y3blndIXkrQpJ5d7
            clientSecret: 3AePzYCVPtkusLcoLefK1E0xq8Sc1Ri8PjJ5UEIn

        provider:
          okta:
            issuerUri: https://dev-34099492.okta.com/oauth2/default



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      CktBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  #retry:
    #instances:
     # CktBreaker:
      #  maxAttempts: 3
       # waitDuration: 2s

  #ratelimiter:
   # instances:
    #  CktBreaker:
     #   limitRefreshPeriod: 4s
      # timeoutDuration: 0s

okta:
  oauth2:
    issuer: https://dev-34099492.okta.com/oauth2/default
    audience: api://default